### ISSUE TITLE
OSRFramework 0.13.1 is installed but throws an error when launching usufy.py

### ISSUE THREAD

**Issue by i3visio** [i3visio/osrframework#154]
The traceback of the error is showing twice the Skype Warning in a Kali Linux fresh install.

```

2016-07-23 09:03:57.131175	Starting search in 232 platform(s)... Relax!

WARNING. Something happened when trying to link to a valid Skype session.
This usually happens when you do NOT have any version of Skype logged in in this machine. Although you may omit this message, you can also fix it by: 
	a) Install any version of  Skype log in
	b) If Skype is installed, the log in window will be appearing. You will need to log in and perform the search again (or run it with '-p skype' only) to get results from Skype.
In spite of this message, execution is going on.
WARNING. Something happened when trying to link to a valid Skype session.
This usually happens when you do NOT have any version of Skype logged in in this machine. Although you may omit this message, you can also fix it by: 
	a) Install any version of  Skype log in
	b) If Skype is installed, the log in window will be appearing. You will need to log in and perform the search again (or run it with '-p skype' only) to get results from Skype.
In spite of this message, execution is going on.
Traceback (most recent call last):
  File "/usr/local/bin/usufy.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/osrframework/osrframework/usufy.py", line 548, in <module>
    main(args)
  File "/root/osrframework/osrframework/usufy.py", line 380, in main
    res = processNickList(nicks, listPlatforms, args.output_folder, avoidProcessing = args.avoid_processing, avoidDownload = args.avoid_download, nThreads=args.threads, verbosity= args.verbose, logFolder=args.logfolder)
  File "/root/osrframework/osrframework/usufy.py", line 239, in processNickList
    array = json.loads(serArray)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

**Comment by i3visio** [comment]
The problem seems to be isolated affecting only the Skype wrapper.
