### ISSUE TITLE
Found an issue when installilng on Windows 0.14.2

### ISSUE THREAD

**Issue by i3visio** [i3visio/osrframework#177]
Found an issue when installing OSRFramework 0.14.2 on Windows regarding `os.geteuid()` which seems not to be available in Windows platforms. Traceback here:
```
C:\Users\<SOMEONE>>pip install osrframework --upgrade
Collecting osrframework
  Using cached osrframework-0.14.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\<SOMEONE>\appdata\local\temp\pip-build-2_du87\osrframework\setup.py", line 32, in <module>
        if not os.geteuid() == 0:
    AttributeError: 'module' object has no attribute 'geteuid'
```

**Comment by i3visio** [comment]
Solved in 0.14.3. Added a check in setup.py before getting the paths for the installation when the system is a Windows machine.
