### ISSUE TITLE
0.15.0rc9 raises an exception if it has upgraded

### ISSUE THREAD

**Issue by i3visio** [i3visio/osrframework#219]
The traceback would seem as follows:
 ```
Traceback (most recent call last):
  File "~.local/bin/usufy.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/path/to/installation/osrframework/usufy.py", line 598, in <module>
    parser = getParser()
  File "/path/to/installation/osrframework/usufy.py", line 571, in getParser
    groupPlatforms.add_argument('-x', '--exclude', metavar='<platform>', choices=platOptions, nargs='+', required=False, default=DEFAULT_VALUES["exclude_platforms"], action='store', help='select the platforms that you want to exclude from the processing.')
KeyError: 'exclude_platforms'
```
The user should be advised to update his/her .cfg files.

**Comment by i3visio** [comment]
Fixed by overwrriing `browser.cfg` and `general.cfg`.
