### ISSUE TITLE
Collecting osrframework

### ISSUE THREAD

**Issue by bluecryptonite** [i3visio/osrframework#252]
pip install osrframework
Collecting osrframework
  Using cached osrframework-0.16.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-o9gr8w22/osrframework/setup.py", line 38
        print "[*] The installation is going to be run as superuser."
                                                                    ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-o9gr8w22/osrframework/

**Comment by i3visio** [comment]
Hi @bluecryptonite! OSRFramework is Python2 only. Can be Python3 installed by default in your current system? If this is the case and assuming that you also have 2.7.x already installed, this may be fixed forcing the usage of `pip2` directly. Two options here. Either:
```
python2 -m pip install osrframework --user
```
Or easier:
```
pip2 install osrframework --user
```
Let's see if this helps!

**Comment by bluecryptonite** [comment]
oh thanx man.. i have 2 python n i apt-get remove python 3 n yes... its
worked

python2 -m pip install osrframework

thanx man..

**Comment by i3visio** [comment]
Great! Do not forget to run `--upgrade` to update your local installation to the latest version periodically. Unfortunately, platforms tend to update their websites _too_ often ;). 

We're closing the issue then!

**Comment by bluecryptonite** [comment]
root@kali:~/Desktop/osrframework# pip install osrframework
Requirement already satisfied: osrframework in
/usr/local/lib/python2.7/dist-packages
Requirement already satisfied: validate-email in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: pyexcel-io==0.1.0 in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: setuptools in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: pyexcel-xls==0.1.0 in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: pyyaml in /usr/lib/python2.7/dist-packages
(from osrframework)
Requirement already satisfied: pyexcel==0.2.1 in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: Skype4Py in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: oauthlib>=1.0.0 in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: pyexcel-text==0.2.0 in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: requests in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: python-emailahoy in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: pyexcel-xlsx==0.1.0 in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: tweepy in /usr/lib/python2.7/dist-packages
(from osrframework)
Requirement already satisfied: BeautifulSoup in
/usr/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: decorator in
/usr/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: mechanize in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: networkx in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: importlib in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: flask in /usr/lib/python2.7/dist-packages
(from osrframework)
Requirement already satisfied: pyexcel-ods==0.1.1 in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: tabulate in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: python-whois in
/usr/local/lib/python2.7/dist-packages (from osrframework)
Requirement already satisfied: pydns in /usr/lib/python2.7/dist-packages
(from osrframework)
Requirement already satisfied: appdirs>=1.4.0 in
/usr/local/lib/python2.7/dist-packages (from setuptools->osrframework)
Requirement already satisfied: packaging>=16.8 in
/usr/local/lib/python2.7/dist-packages (from setuptools->osrframework)
Requirement already satisfied: six>=1.6.0 in
/usr/lib/python2.7/dist-packages (from setuptools->osrframework)
Requirement already satisfied: xlrd in
/usr/local/lib/python2.7/dist-packages (from
pyexcel-xls==0.1.0->osrframework)
Requirement already satisfied: xlwt-future in
/usr/local/lib/python2.7/dist-packages (from
pyexcel-xls==0.1.0->osrframework)
Requirement already satisfied: texttable>=0.8.2 in
/usr/local/lib/python2.7/dist-packages (from pyexcel==0.2.1->osrframework)
Requirement already satisfied: openpyxl==2.2.2 in
/usr/local/lib/python2.7/dist-packages (from
pyexcel-xlsx==0.1.0->osrframework)
Requirement already satisfied: html5lib>=0.999999999 in
/usr/local/lib/python2.7/dist-packages (from mechanize->osrframework)
Requirement already satisfied: odfpy==0.9.6 in
/usr/local/lib/python2.7/dist-packages (from
pyexcel-ods==0.1.1->osrframework)
Requirement already satisfied: future in
/usr/local/lib/python2.7/dist-packages (from python-whois->osrframework)
Requirement already satisfied: pyparsing in
/usr/local/lib/python2.7/dist-packages (from
packaging>=16.8->setuptools->osrframework)
Requirement already satisfied: jdcal in
/usr/local/lib/python2.7/dist-packages (from
openpyxl==2.2.2->pyexcel-xlsx==0.1.0->osrframework)
Requirement already satisfied: webencodings in
/usr/local/lib/python2.7/dist-packages (from
html5lib>=0.999999999->mechanize->osrframework)
root@kali:~/Desktop/osrframework# osrfconsole.py
bash: /usr/local/bin/osrfconsole.py: Permission denied

**Comment by i3visio** [comment]
Hi again @bluecryptonite,

We have not been able to replicate the issue in a fresh install of Kali Linux (see image attached, only command run is `pip install osrframework`).
![seleccion_811](https://cloud.githubusercontent.com/assets/8018610/25887236/7c21bd20-3561-11e7-8de9-7f721a24c180.png)
Can you try again by uninstalling any previously loaded installation using `pip uninstall osrframework`?

**Comment by i3visio** [comment]
Have you been able to reproduce that behaviour?

**Comment by 1plat** [comment]
![image](https://user-images.githubusercontent.com/78534099/106871493-57b4ad00-66e3-11eb-9b81-f464d1822bfe.png)
