### ISSUE TITLE
Issue when running osrfconsole.py

### ISSUE THREAD

**Issue by i3visio** [i3visio/osrframework#264]
When running osrfconsole.py, it is lately throwing an exception:
```
osrfconsole.py
osrf > use usufy

osrf (usufy) > set NICK i3visio

osrf (usufy) > info
Traceback (most recent call last):
  File "/usr/local/bin/osrfconsole.py", line 1027, in <module>
    OSRFConsoleMain().cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/local/bin/osrfconsole.py", line 1005, in do_use
    OSRFConsoleUsufy().cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/local/bin/osrfconsole.py", line 273, in do_info
    self.do_show("command")
  File "/usr/local/bin/osrfconsole.py", line 234, in do_show
    print "Equivalent command to be launched to imitate the current configuration:\n\t$ " + self.createCommandLine()
  File "/usr/local/bin/osrfconsole.py", line 258, in createCommandLine
    params = self._getParams()
  File "/usr/local/bin/osrfconsole.py", line 878, in _getParams
    "-e" ] + self.CONFIG["EXTENSION"]["CURRENT_VALUE"].split()
AttributeError: 'list' object has no attribute 'split'

```
Some rrror capturing needs to be done.

**Comment by i3visio** [comment]
Fixed and is now being addressed at https://github.com/i3visio/osrframework_console
