### ISSUE TITLE
mailfy throws error: No module named deprecated. 

### ISSUE THREAD

**Issue by adgpt** [i3visio/osrframework#301]
Please have a look at this: 

`root@kali:~# mailfy.py -m "<Email address of the target>"

  ___  ____  ____  _____                                            _
 / _ \/ ___||  _ \|  ___| __ __ _ _ __ ___   _____      _____  _ __| | __
| | | \___ \| |_) | |_ | '__/ _` | '_ ` _ \ / _ \ \ /\ / / _ \| '__| |/ /
| |_| |___) |  _ <|  _|| | | (_| | | | | | |  __/\ V  V / (_) | |  |   <
 \___/|____/|_| \_\_|  |_|  \__,_|_| |_| |_|\___| \_/\_/ \___/|_|  |_|\_

                Version:      OSRFramework 0.17.2
                Created by:   Felix Brezo and Yaiza Rubio, (i3visio)

mailfy.py Copyright (C) F. Brezo and Y. Rubio (i3visio) 2016-2017

This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you
are welcome to redistribute it under certain conditions. For additional info,
visit https://www.gnu.org/licenses/agpl-3.0.txt

2018-01-13 08:34:59.801947	Starting search in 1 different emails:
[
  "<Email Address of the target>"
]

	Press <Ctrl + C> to stop...

2018-01-13 08:35:00.955783	Mailfy has found 1 existing email(s). Has it been leaked somewhere?
	<Email address of the target> has NOT been found on any leak yet.

2018-01-13 08:35:03.895580	A summary of the results obtained are shown in the following table:

Traceback (most recent call last):
  File "/usr/local/bin/mailfy.py", line 658, in <module>
    main(args)
  File "/usr/local/bin/mailfy.py", line 587, in main
    print(general.success(general.usufyToTextExport(results)))
  File "/usr/lib/python2.7/dist-packages/osrframework/utils/general.py", line 305, in usufyToTextExport
    import pyexcel as pe
  File "/usr/lib/python2.7/dist-packages/pyexcel/__init__.py", line 44, in <module>
    from .cookbook import (
  File "/usr/lib/python2.7/dist-packages/pyexcel/cookbook.py", line 12, in <module>
    from .sources import get_book, get_sheet, save_as
  File "/usr/lib/python2.7/dist-packages/pyexcel/sources/__init__.py", line 22, in <module>
    from . import memory, file, database, http
  File "/usr/lib/python2.7/dist-packages/pyexcel/sources/memory.py", line 10, in <module>
    from pyexcel_io.deprecated import load_data
ImportError: No module named deprecated
`
Every time I try to run mailfy, this error pops up. I'm new to OSRFramework. 
Please help.

**Comment by i3visio** [comment]
Sorry for the delay @adgpt. Can you show what is the result of? Is it 0.1.0 or later?
```
pip2 list | grep pyexcel-io
```

**Comment by adgpt** [comment]
`root@kali:~# pip2 list | grep pyexcel-io
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pyexcel-io (0.1.0)`

Ran the command and this is the output.

**Comment by i3visio** [comment]
Ok, so it seems that it is not a pyexcel_io problem but maybe just a pyexcel dependency. Note that the most recent pyexcel package available in pip is 0.5.7 but because of some legacy functions we use in OSRFramework the one we require is 0.2.1. As we are not sure if this is the real issue, can you confirm that you have installed in your system 0.2.1? 

In our case:
```
> pip2 list | grep pyexcel
pyexcel (0.2.1)
pyexcel-io (0.1.0)
pyexcel-ods (0.1.1)
pyexcel-text (0.2.0)
pyexcel-xls (0.1.0)
pyexcel-xlsx (0.1.0)
```
So as to try to avoid future problems, we are creating a new issue to avoid the freezing of such an old dependency. We may need some adjustments in the code to keep it compatible with most recent versions of pyexcel, which is still under development.

**Comment by i3visio** [comment]
By the way, the issue we have created is https://github.com/i3visio/osrframework/issues/307. Just to keep track of this in the future.
