### ISSUE TITLE
Problem with the execution

### ISSUE THREAD

**Issue by MrAlgoRnadom** [i3visio/osrframework#358]
I have a Linux distribution as OS. I have installed the git clone, the requirements and the setup.py, just in case. I have tried the command: "osrf", but this is the result of the terminal:

Traceback (most recent call last):
  File "/usr/local/bin/osrf", line 11, in <module>
    load_entry_point('osrframework==0.20.2b1', 'console_scripts', 'osrf')()
  File "/usr/local/lib/python3.6/dist-packages/osrframework-0.20.2b1-py3.6.egg/osrframework/launcher.py", line 136, in main
    parser = get_parser()
  File "/usr/local/lib/python3.6/dist-packages/osrframework-0.20.2b1-py3.6.egg/osrframework/launcher.py", line 85, in get_parser
    parents=[domainfy.get_parser()]
  File "/usr/local/lib/python3.6/dist-packages/osrframework-0.20.2b1-py3.6.egg/osrframework/domainfy.py", line 449, in get_parser
    group_processing.add_argument('-e', '--extension', metavar='<sum_ext>', nargs='+', choices=['csv', 'gml', 'json', 'ods', 'png', 'txt', 'xls', 'xlsx' ], required=False, default=DEFAULT

Thanks in advance. If anyone could give me a hand, it would be very useful for me.

**Comment by MrAlgoRnadom** [comment]
Well, trying to run the sections with "sudo" let me run the code normally. I think it was a problem of writing the commands. Thanks anyway.

**Comment by Tony-Finn** [comment]
Doesn't work as root
