### ISSUE TITLE
cant use any functionality of the framework

### ISSUE THREAD

**Issue by yoavoffek** [i3visio/osrframework#359]
getting these errors when i try to use any of the framework functionalities:
C:\Users\offek>usufy.py -h
Traceback (most recent call last):
  File "C:\Users\offek\AppData\Local\Programs\Python\Python38-32\Scripts\usufy.py-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\offek\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 3262, in <module>
    def _initialize_master_working_set():
  File "c:\users\offek\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 3245, in _call_aside
    f(*args, **kwargs)
  File "c:\users\offek\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 3274, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\offek\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "c:\users\offek\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\offek\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PySocks!=1.5.7,>=1.5.6; extra == "socks"' distribution was not found and is required by requests

**Comment by netoeuler** [comment]
I had already got this error and it was resolved with `pip3 install PySocks`
