### ISSUE TITLE
domainfy throwing syntax error

### ISSUE THREAD

**Issue by akshai-tr** [i3visio/osrframework#367]
domainfy tool in the OSRFramework always returns syntax error. Below is the log when I ran `domainfy --help`

```plaintext
# domainfy --help

Traceback (most recent call last):
  File "/usr/local/bin/domainfy", line 5, in <module>
    from osrframework.domainfy import main
  File "/usr/local/lib/python3.9/dist-packages/osrframework/domainfy.py", line 452
    group_processing.add_argument('-u', '--user-defined', metavar='<new_tld>', nargs='+', action='store', help='additional TLD that will be searched.', required=False, default=DEFAULT_VALUES.get("user_defined", []))
    ^
SyntaxError: invalid syntax
```

**Comment by alsunseri** [comment]
Sorry to cross post.  - I saw #368 before i saw this one.
The problem is with line 451. ( version 0.20.2 via pip3 )
It is missing an end parenthesis.
I added the parenthesis and got another error.
In addition to adding the end parenthesis change DEFAULT_VALUE to DEFAULT_VALUES - also on line 451
Anyway, the syntax error is a missing ')' on line 451 of domainfy.py

This is for version 0.20.2 installed via pip3
But it seems to work if i make those 2 changes.

**Comment by akshai-tr** [comment]
@alsunseri Thanks for the help. It is working fine now.

**Comment by akshai-tr** [comment]
@alsunseri You could raise a PR for to fix this issue in the repo :smiley_cat: 
cc @i3visio

**Comment by alsunseri** [comment]
Glad to hear.
But I cant do a pull request as far as I can tell  for two reasons. 

The domainfy.py here on github is a different version and it does not have either of those typos it seems. 

I don't know why - but the github code here is a different version ( 0.18.8 vs 0.20.2 ) from the pip version. 
I can not find version 0.20.2 on github.
