### ISSUE TITLE
Error in running $sudo osrf --help

### ISSUE THREAD

**Issue by Mayank-Khurmai** [i3visio/osrframework#368]
Traceback (most recent call last):
  File "/usr/local/bin/osrf", line 5, in <module>
    from osrframework.launcher import main
  File "/usr/local/lib/python3.8/dist-packages/osrframework/launcher.py", line 28, in <module>
    import osrframework.domainfy as domainfy
  File "/usr/local/lib/python3.8/dist-packages/osrframework/domainfy.py", line 452
    group_processing.add_argument('-u', '--user-defined', metavar='<new_tld>', nargs='+', action='store', help='additional TLD that will be searched.', required=False, default=DEFAULT_VALUES.get("user_defined", []))
    ^
SyntaxError: invalid syntax

**Comment by alsunseri** [comment]
I encountered the same problem. On both kali 2020.4 and Parrot Linux 4.10 
I have not tried the install anywhere else yet.

**Comment by akshai-tr** [comment]
Seems like this issue is similar to https://github.com/i3visio/osrframework/issues/367

**Comment by jjr207** [comment]
Having the same problem, and yes it seems the same as #367

**Comment by alsunseri** [comment]
The problem is with line 451.  ( version  0.20.2 via pip3  ) 
It is missing an end parenthesis. 
I added the parenthesis and got another error. 
In addition to adding the end parenthesis change  DEFAULT_VALUE to DEFAULT_VALUES - also on line 451
Anyway, the syntax error is a missing ')' on line 451 of domainfy.py 

This is for version 0.20.2 installed via pip3 
But it seems to work if i make those 2 changes.

**Comment by jjr207** [comment]
alsunseri.  Many thanks!  Works perfectly now.

**Comment by talhaschoice** [comment]
This didnt work for me, had a lot of problem and headache solving, 
finally found the solution. The problem is with this latest version of osrf.
tried uninstalling and reinstalling with older version specifically.

sudo pip uninstall osrframework

pip install osrframework==0.20.0
