### ISSUE TITLE
mailfy error

### ISSUE THREAD

**Issue by kedipaiyan2425** [i3visio/osrframework#370]
while execute
>> mail.py -m e-mail

i got an error 

[*] 'mailfy' is not a valid mode for this wrapper (Facebook).
Traceback (most recent call last):
  File "/usr/local/bin/mailfy.py", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/osrframework/mailfy.py", line 501, in main
    registered = process_mail_list_step_2(platforms=platforms, emails=emails)
  File "/usr/local/lib/python3.8/dist-packages/osrframework/mailfy.py", line 349, in process_mail_list_step_2
    entities = pla.do_mailfy(query=e)
  File "/usr/local/lib/python3.8/dist-packages/osrframework/utils/platforms.py", line 367, in do_mailfy
    if self.check_mailfy(query, **kwargs):
  File "/usr/local/lib/python3.8/dist-packages/osrframework/wrappers/instagram.py", line 128, in check_mailfy
    csrf_token = re.findall("csrf_token", r1.text)[0]
IndexError: list index out of range

**Comment by se7enge** [comment]
I am also having the same/very similar issue using mailfy.py. It seems that after it passes step 2 it always returns the following, no matter what:

[*] Starting the research of 1 email(s) in 5 platform(s)... This may take a while.

        [*] 1/1 Checking 'example@hotmail.com'...
Traceback (most recent call last):
  File "/usr/bin/mailfy.py", line 11, in <module>
    load_entry_point('osrframework==0.20.1', 'console_scripts', 'mailfy.py')()
  File "/usr/lib/python3/dist-packages/osrframework/mailfy.py", line 502, in main
    registered = process_mail_list_step_2(platforms=platforms, emails=emails)
  File "/usr/lib/python3/dist-packages/osrframework/mailfy.py", line 349, in process_mail_list_step_2
    entities = pla.get_info(query=e, mode="mailfy")
  File "/usr/lib/python3/dist-packages/osrframework/utils/platforms.py", line 152, in get_info
    results = getattr(self, "do_{}".format(mode))(query)
  File "/usr/lib/python3/dist-packages/osrframework/utils/platforms.py", line 352, in do_mailfy
    if self.check_mailfy(query, **kwargs):
  File "/usr/lib/python3/dist-packages/osrframework/wrappers/instagram.py", line 128, in check_mailfy
    csrf_token = re.findall("csrf_token", r1.text)[0]
IndexError: list index out of range

Perhaps I am missing some python dependencies that I am not aware of? I'm sure there is a reasonable explanation, but unfortunately I am relatively new to this so it is not apparent.

Any advice is much appreciated :)

**Comment by rapbando** [comment]
Same error here:

`Traceback (most recent call last):
  File "/usr/bin/osrf", line 11, in <module>
    load_entry_point('osrframework==0.20.1', 'console_scripts', 'osrf')()
  File "/usr/lib/python3/dist-packages/osrframework/launcher.py", line 152, in main
    module.main(args)
  File "/usr/lib/python3/dist-packages/osrframework/mailfy.py", line 502, in main
    registered = process_mail_list_step_2(platforms=platforms, emails=emails)
  File "/usr/lib/python3/dist-packages/osrframework/mailfy.py", line 349, in process_mail_list_step_2
    entities = pla.get_info(query=e, mode="mailfy")
  File "/usr/lib/python3/dist-packages/osrframework/utils/platforms.py", line 152, in get_info
    results = getattr(self, "do_{}".format(mode))(query)
  File "/usr/lib/python3/dist-packages/osrframework/utils/platforms.py", line 352, in do_mailfy
    if self.check_mailfy(query, **kwargs):
  File "/usr/lib/python3/dist-packages/osrframework/wrappers/instagram.py", line 128, in check_mailfy
    csrf_token = re.findall("csrf_token", r1.text)[0]
IndexError: list index out of range
`

**Comment by rapbando** [comment]
After looking at instagram.py one reason for sure is the `csrf_token` field that has changed to `csfrtoken` but even changing this value used in the /accounts/web_create_ajax/attempt/ HTTP/1.1 POST call, the error is still there. Now there must be more values to validate and reduce the requests to  instagram  before the site sends back the response with the clues if the email address is taken or not.
![Screenshot_2021-09-21_22-15-46](https://user-images.githubusercontent.com/3671551/134242610-19ade13d-c991-4761-b12e-691233e5e5a5.png)
