### ISSUE TITLE
Traceback issue

### ISSUE THREAD

**Issue by HumanInjection** [i3visio/osrframework#381]
I Have this issue, I dont know whats that mean, please help me

└─$ osrf --help
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/osrframework/utils/updates.py", line 22, in <module>
    from pip._internal.utils.misc import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/osrf", line 5, in <module>
    from osrframework.launcher import main
  File "/usr/local/lib/python3.10/dist-packages/osrframework/launcher.py", line 33, in <module>
    import osrframework.upgrade as upgrade
  File "/usr/local/lib/python3.10/dist-packages/osrframework/upgrade.py", line 30, in <module>
    from osrframework.utils.updates import UpgradablePackage
  File "/usr/local/lib/python3.10/dist-packages/osrframework/utils/updates.py", line 24, in <module>
    from pip import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip' (/usr/lib/python3/dist-packages/pip/__init__.py)

**Comment by atanu2679** [comment]
└─# osrf --help                             
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/osrframework/utils/updates.py", line 22, in <module>
    from pip._internal.utils.misc import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/misc.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/osrf", line 33, in <module>
    sys.exit(load_entry_point('osrframework==0.20.5', 'console_scripts', 'osrf')())
  File "/usr/local/bin/osrf", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/osrframework/launcher.py", line 33, in <module>
    import osrframework.upgrade as upgrade
  File "/usr/local/lib/python3.10/dist-packages/osrframework/upgrade.py", line 30, in <module>
    from osrframework.utils.updates import UpgradablePackage
  File "/usr/local/lib/python3.10/dist-packages/osrframework/utils/updates.py", line 24, in <module>
    from pip import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip' (/usr/local/lib/python3.10/dist-packages/pip/__init__.py)



same error.....................

**Comment by ridoutdev** [comment]
Use  -->  $ usufy.py -h

**Comment by Korede01** [comment]
Really dont know what to do here:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/osrframework/utils/updates.py", line 22, in <module>
    from pip._internal.utils.misc import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/osrf", line 5, in <module>
    from osrframework.launcher import main
  File "/usr/local/lib/python3.10/dist-packages/osrframework/launcher.py", line 33, in <module>
    import osrframework.upgrade as upgrade
  File "/usr/local/lib/python3.10/dist-packages/osrframework/upgrade.py", line 30, in <module>
    from osrframework.utils.updates import UpgradablePackage
  File "/usr/local/lib/python3.10/dist-packages/osrframework/utils/updates.py", line 24, in <module>
    from pip import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip' (/usr/lib/python3/dist-packages/pip/__init__.py)



How do i access folder: osrframework-master/osrframework
