### ISSUE TITLE
ImportError: cannot import name 'get_installed_distributions' from 'pip'

### ISSUE THREAD

**Issue by FalcoGer** [i3visio/osrframework#382]
I have upgraded to python3.10 with pip version 22.3.1. I tried using this tool again and tried to upgrade it, but now I get the following error message.

```bash
pip3 install -U osrframework
# [output, no errors]
osrf -h
```

```text
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/osrframework/utils/updates.py", line 22, in <module>
    from pip._internal.utils.misc import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (/home/username/.local/lib/python3.10/site-packages/pip/_internal/utils/misc.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/.local/bin/osrf", line 5, in <module>
    from osrframework.launcher import main
  File "/home/username/.local/lib/python3.10/site-packages/osrframework/launcher.py", line 33, in <module>
    import osrframework.upgrade as upgrade
  File "/home/username/.local/lib/python3.10/site-packages/osrframework/upgrade.py", line 30, in <module>
    from osrframework.utils.updates import UpgradablePackage
  File "/home/username/.local/lib/python3.10/site-packages/osrframework/utils/updates.py", line 24, in <module>
    from pip import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip' (/home/username/.local/lib/python3.10/site-packages/pip/__init__.py)
```

**Comment by FalcoGer** [comment]
Temporary workaround is to have a virtual environment (`virtualenv`) and downgrading pip with `pip install -U 'pip<21.3'`
