### ISSUE TITLE
[error after installing] Traceback (most recent call last):

### ISSUE THREAD

**Issue by cabiamdos** [i3visio/osrframework#384]
Hello, I am using kali linux and I am getting this error. I have also cloned the repository and installed all the requirements but doesn't work
```

>> osrf
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/osrframework/utils/updates.py", line 22, in <module>
    from pip._internal.utils.misc import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/osrf", line 5, in <module>
    from osrframework.launcher import main
  File "/usr/local/lib/python3.10/dist-packages/osrframework/launcher.py", line 33, in <module>
    import osrframework.upgrade as upgrade
  File "/usr/local/lib/python3.10/dist-packages/osrframework/upgrade.py", line 30, in <module>
    from osrframework.utils.updates import UpgradablePackage
  File "/usr/local/lib/python3.10/dist-packages/osrframework/utils/updates.py", line 24, in <module>
    from pip import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip' (/usr/lib/python3/dist-packages/pip/__init__.py)
```

**Comment by defendintegrity** [comment]
I have the same issue. any idea?

**Comment by juancho-debug** [comment]
yeap  i am installing it in ubuntu and i had the same problem , i updated the pip3 and it seem to work but after the instalation it does not found any commands like osrframework or mailfy .
