### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by foysal-ahamed** [i3visio/osrframework#389]
Recently I installed and got this error.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/osrframework/utils/configuration.py", line 156, in get_configuration_values_for
    with open(defaultConfigPath) as iF:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/foysal/.config/OSRFramework/default/general.cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/osrf", line 11, in <module>
    load_entry_point('osrframework==0.20.1', 'console_scripts', 'osrf')()
  File "/usr/lib/python3/dist-packages/osrframework/launcher.py", line 136, in main
    parser = get_parser()
             ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/osrframework/launcher.py", line 80, in get_parser
    parents=[checkfy.get_parser()]
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/osrframework/checkfy.py", line 84, in get_parser
    DEFAULT_VALUES = configuration.get_configuration_values_for("checkfy")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/osrframework/utils/configuration.py", line 162, in get_configuration_values_for
    raise errors.DefaultConfigurationFileNotFoundError(configPath, defaultConfigPath);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
osrframework.utils.errors.DefaultConfigurationFileNotFoundError: 
        - Oh! What's happening? > The configuration file /home/foysal/.config/OSRFramework/general.cfg could not be found. The system tried to get the files provided by default with OSRFramework but they were not found either.
        - How can I solve this? > Check if the configuration path exists or if it is accesible by the current user. You should be able to find the default configuration files at '/home/foysal/.config/OSRFramework/default/general.cfg'. If they are not there, try to solve this by reinstalling OSRFramework again for this user.
```
Please help me

**Comment by MohitGoyal19** [comment]
You can create a blank configuration file to avoid this issue.

You can use the following command to do the same:
`touch /home/foysal/.config/OSRFramework/default/general.cfg `
