### ISSUE TITLE
Compatibility Issue with python (>=3.8) and pip

### ISSUE THREAD

**Issue by MohitGoyal19** [i3visio/osrframework#391]
`Traceback (most recent call last):
  File "/usr/local/bin/osrf", line 5, in <module>
    from osrframework.launcher import main
  File "/usr/local/lib/python3.10/dist-packages/osrframework/launcher.py", line 33, in <module>
    import osrframework.upgrade as upgrade
  File "/usr/local/lib/python3.10/dist-packages/osrframework/upgrade.py", line 30, in <module>
    from osrframework.utils.updates import UpgradablePackage
  File "/usr/local/lib/python3.10/dist-packages/osrframework/utils/updates.py", line 24, in <module>
    from pip import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip' (/home/zero/.local/lib/python3.10/site-packages/pip/__init__.py)
`

This error is coming in newer versions of Python and pip

**Comment by pikpikcu** [comment]
solved - https://github.com/i3visio/osrframework/pull/397
