### ISSUE TITLE
Launching usufy.py -n <nick> -p wikipedia makes the program crash 

### ISSUE THREAD

**Issue by i3visio** [i3visio/osrframework#52]
When launching usufy.py throws the following exception:
```
	Starting search in 0 platform(s)... Be patient!

Traceback (most recent call last):
  File "usufy.py", line 565, in <module>
    main(args)
  File "usufy.py", line 399, in main
    res = processNickList(nicks, listPlatforms, args.output_folder, avoidProcessing = args.avoid_processing, avoidDownload = args.avoid_download, nThreads=args.threads, verbosity= args.verbose, logFolder=args.logfolder)
  File "usufy.py", line 225, in processNickList
    pool = Pool(nThreads)
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 152, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

It seems to be an issue with the way in which the number of threads is calculated related to the fact that by doing -p wikipedia all the Wikipedia platforms are queried.

**Comment by i3visio** [comment]
Corrected and pending of being updated upstream.
