### ISSUE TITLE
Issue when installing in Windows v0.11.x

### ISSUE THREAD

**Issue by i3visio** [i3visio/osrframework#93]
There is an issue when installing the first bet in Windows regarding the method used to change the permissions of certain files. Exceptions need to be grabbed and processed accordingly:

```
pip install osrframework --upgrade --pre
Collecting osrframework
  Downloading osrframework-0.11.0b0.tar.gz (154kB)
    100% |################################| 155kB 890kB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\osrframework.egg-info
    writing requirements to pip-egg-info\osrframework.egg-info\requires.txt
    writing pip-egg-info\osrframework.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\osrframework.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\osrframework.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\osrframework.egg-info\SOURCES.txt'
    C:\Python27\lib\site-packages\setuptools\dist.py:285: UserWarning: Normalizing '0.11.0b' to '0.11.0b0
'
      normalized_version,
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info\osrframework.egg-info\SOURCES.txt'
    writing manifest file 'pip-egg-info\osrframework.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\<USER>\appdata\local\temp\pip-build-ddtxni\osrframework\setup.py", line 151, in <modu
le>
        general.changePermissionsRecursively(applicationPath, int(os.getenv('SUDO_UID')), int(os.getenv('
SUDO_GID')))
    TypeError: int() argument must be a string or a number, not 'NoneType'

```

**Comment by i3visio** [comment]
Seems to be linked to issue #98. Verification pending.
